content:
  - name: posts
    label: 블로그 포스트
    type: collection
    path: content/posts
    format: md
    # {title}이 치환되지 않는다면 아래와 같이 'slug'를 활용하는 것이 가장 안전합니다.
    filename: "{year}-{month}-{day}-{slug}" 
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      # slug 필드를 추가하면 파일명을 더 안정적으로 생성할 수 있습니다.
      - name: slug
        label: URL 슬러그 (파일명)
        type: string
        help: 영어와 대시(-)만 사용하세요 (예: my-first-post)
      - name: date
        label: 날짜
        type: datetime
        default: now
      - name: draft
        label: 초안 여부
        type: boolean
        default: false
      - name: body
        label: 본문 내용
        type: rich-text
