# 저장소 최상위 루트의 .pagescms.yml 내용
content:
  - name: Posts
    label: 블로그 포스트
    type: collection
    path: content/posts
    format: md
    # 파일이 생성될 때의 규칙입니다.
    filename: "{year}-{month}-{day}-{slug}"
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      - name: date
        label: 날짜
        type: datetime
        default: now
      - name: body
        label: 본문
        type: rich-text
