content:
  - name: posts
    label: 블로그 포스트
    type: collection
    path: content/posts
    format: md
    # 중괄호 2개를 사용하고 앞에 날짜를 붙여주면 한글 제목도 더 잘 인식됩니다.
    filename: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      - name: date
        label: 날짜
        type: datetime
        default: now
      - name: draft
        label: 초안 여부
        type: boolean
        default: false
      - name: body
        label: 본문 내용
        type: rich-text
