content:
  - name: posts
    label: 블로그 포스트
    type: collection
    path: content/posts
    format: md
    # {slug} 대신 {title}을 직접 파일명에 사용하도록 변경
    filename: "{year}-{month}-{day}-{title}"
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      - name: date
        label: 날짜
        type: datetime
        default: now
      - name: body
        label: 본문
        type: rich-text
