content:
  - name: posts
    label: 블로그 포스트
    type: collection
    path: content/posts
    filename: "{date:YYYY-MM-DD}-{fields.title}.md"  # 여기서 .md 추가 필수!
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      - name: date
        label: 날짜
        type: datetime
        default: now
      - name: draft
        label: 초안
        type: boolean
        default: true
      - name: description
        label: 요약
        type: string
      - name: categories
        label: 카테고리
        type: list
      - name: tags
        label: 태그
        type: list
      - name: cover
        label: 대표 이미지
        type: image
      - name: body
        label: 본문
        type: rich-text