content:
  - name: posts
    label: 포스트
    type: collection
    path: content/posts
    format: md
    fields:
      - name: title
        label: 제목
        type: string
      - name: body
        label: 본문
        type: rich-text
