content:
  - name: Posts
    type: collection
    path: content/posts
    format: md
    filename: "{year}-{month}-{day}-{title}" # 파일명에 제목이 포함되도록 설정
    fields:
      - name: title
        type: string
        label: 제목
        required: true # 제목을 필수로 입력하게 설정
      - name: date
        type: datetime
        label: 날짜
      - name: draft
        type: boolean
        label: 초안 여부
        default: false
      - name: body
        type: rich-text
        label: 본문